# samconfig.localstack.toml
version = 0.1

[default.deploy.parameters]
stack_name = "chat-sam-app"
resolve_s3 = true
s3_prefix = "chat-sam-app"
region = "ap-northeast-1"
profile = "localstack"
capabilities = "CAPABILITY_IAM"
image_repositories = []