# yaml-language-server: $schema=https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Chat SAM app stack — メッセージ閲覧/投稿、セッション管理、定期 Bot 生成 を仕様どおり実装

Parameters:
  Prefix:
    Type: String
    Default: "chat-sam-app"
    Description: "リソース名に付与するプレフィックス"

Globals:
  Function:
    Timeout: 3 # 秒
    MemorySize: 256 # MB
    Environment:
      Variables:
        MESSAGE_TABLE: !Ref MessageTable
        MESSAGE_COUNTER_TABLE: !Ref MessageCounterTable
        SESSION_TABLE: !Ref SessionTable
        COUNTER_RANGE_TABLE: !Ref CounterRangeTable
        DUMMY_VALUE: "ALL"
        CREATED_AT_GSI: CreatedAtIndex
        LOGO_BUCKET: !Ref LogoBucket

Resources:
  # ------------------------
  # Cognito User Pool & Client
  # ------------------------
  ChatUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${Prefix}-UserPool"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  ChatUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${Prefix}-UserPoolClient"
      UserPoolId: !Ref ChatUserPool
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - "https://oauth.pstmn.io/v1/callback"
      SupportedIdentityProviders:
        - "COGNITO"
      AllowedOAuthFlows:
        - "code"
      AllowedOAuthScopes:
        - "openid"

  ChatUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${Prefix}-chat-domain"
      UserPoolId: !Ref ChatUserPool

  # ------------------------
  # API
  # ------------------------
  ChatApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: ChatAuthorizer
        Authorizers:
          ChatAuthorizer:
            UserPoolArn: !GetAtt ChatUserPool.Arn
            Identity:
              Header: Authorization

  # ------------------------
  # Chat Lambda
  # ------------------------
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/chat-function
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessageTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTable
        - DynamoDBReadPolicy:
            TableName: !Ref CounterRangeTable
        - DynamoDBCrudPolicy:
            TableName: !Ref MessageCounterTable
        - S3ReadPolicy:
            BucketName: !Ref LogoBucket
      Events:
        GetMessages:
          Type: Api
          Properties:
            Path: /messages
            Method: GET
            RestApiId: !Ref ChatApi
        PostMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: POST
            RestApiId: !Ref ChatApi
        GetLatestMessages:
          Type: Api
          Properties:
            Path: /messages/latest
            Method: GET
            RestApiId: !Ref ChatApi
        StaticIndex:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ChatApi
        GetAdminInfo:
          Type: Api
          Properties:
            Path: /message-counter
            Method: GET
            RestApiId: !Ref ChatApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - app.ts

  ChatFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ChatFunction}"
      RetentionInDays: 3

  # ------------------------
  # DynamoDB テーブル群（Prefix を付与）
  # ------------------------
  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Prefix}-SessionTable"
      AttributeDefinitions:
        - AttributeName: SessionId
          AttributeType: S
      KeySchema:
        - AttributeName: SessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ExpirationDate
        Enabled: true

  MessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Prefix}-MessageTable"
      AttributeDefinitions:
        - AttributeName: MessageNo
          AttributeType: N
        - AttributeName: CreatedAt
          AttributeType: N
        - AttributeName: Dummy
          AttributeType: S
      KeySchema:
        - AttributeName: Dummy
          KeyType: HASH
        - AttributeName: MessageNo
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: CreatedAtIndex
          KeySchema:
            - AttributeName: Dummy
              KeyType: HASH
            - AttributeName: CreatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  MessageCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Prefix}-MessageCounterTable"
      AttributeDefinitions:
        - AttributeName: CounterId
          AttributeType: S
      KeySchema:
        - AttributeName: CounterId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CounterRangeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Prefix}-CounterRangeTable"
      AttributeDefinitions:
        - AttributeName: RecordId
          AttributeType: S
      KeySchema:
        - AttributeName: RecordId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ExpirationDate
        Enabled: true

  # ------------------------
  # S3 バケット (LogoBucket) — Prefix を付与
  # ------------------------
  LogoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Prefix}-logo-bucket"
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ["*"]
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedHeaders: ["*"]
            MaxAge: 3000
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

Outputs:
  SessionTableName:
    Description: "Name of SessionTable"
    Value: !Ref SessionTable

  MessageTableName:
    Description: "Name of MessageTable"
    Value: !Ref MessageTable

  MessageCounterTableName:
    Description: "Name of MessageCounterTable"
    Value: !Ref MessageCounterTable

  CounterRangeTableName:
    Description: "Name of CounterRangeTable"
    Value: !Ref CounterRangeTable

  LogoBucketName:
    Description: "Name of S3 bucket for logos"
    Value: !Ref LogoBucket

  # API の URL を出力するならこちら
  ChatApiUrl:
    Description: "Base URL for Chat API"
    Value: !Sub "https://${ChatApi}.execute-api.${AWS::Region}.amazonaws.com/${ChatApi.Stage}"
